name: enter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: null
  dartz: null
  flutter:
    sdk: flutter
  freezed_annotation: null
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: null
  get_storage: null
  http: ^0.13.5
  json_serializable: null
  rxdart: null
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.4

  flutter_test:
    sdk: flutter
  freezed: null

flutter:
  uses-material-design: true
